//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tolstoy_Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tolstoy_Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 867936
        ///870834
        ///853614
        ///853574
        ///624937
        ///853353
        ///858824
        ///972082
        ///972520
        ///972745
        ///853315.
        /// </summary>
        internal static string Adminsid {
            get {
                return ResourceManager.GetString("Adminsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 981432
        ///981430
        ///981429
        ///981427
        ///981426
        ///981425
        ///981414
        ///981408
        ///981407
        ///981406
        ///981402
        ///981400
        ///981399
        ///981398
        ///981397
        ///981396
        ///981395
        ///981394
        ///981393
        ///981392
        ///981391
        ///981390
        ///981389
        ///981388
        ///981386
        ///981385
        ///981384
        ///981383
        ///981382
        ///981381
        ///981381
        ///980713
        ///980708
        ///980707
        ///980669
        ///980668
        ///980655
        ///980648
        ///980647
        ///980629
        ///980628
        ///978855
        ///978852
        ///978847
        ///978845
        ///978844
        ///978843
        ///978842
        ///978841
        ///978838
        ///978837
        ///978833
        ///978831
        ///978828
        ///978826
        ///978824
        ///978822
        ///978821
        ///978813
        ///978812
        ///978811
        ///978810
        ///978809
        ///978803
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Botsid {
            get {
                return ResourceManager.GetString("Botsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
